### ISSUE TITLE
[Quest][Horde][Barrens] - Verog the Dervish

### ISSUE THREAD

**Issue by LevanSturua** [LevanSturua/common-core-db-bugs#1]
**აღწერა**: მობი რომელიც ქვესთისთვის უნდა მოკლა არ ჩნდება

**როგორ მუშაობს:** საერთოდ არ ჩნდება NPC

**როგორ უნდა მუშაობდეს:** გარშემო რამოდენიმე კენტავრის მოკვლის შემდეგ http://www.wowhead.com/npc=3395/verog-the-dervish უნდა ჩნდებოდეს, რომლის მოკვლის შემდეგაც შეგეძლება http://www.wowhead.com/item=5023/verogs-head აღება.

https://www.youtube.com/watch?v=s4tY7eWOFQs

**როგორ შევამოწმოთ:** 
1.  .add quest 851
2. მივიდეთ ბარრენსში ამ ადგილას
![barrens](https://cloud.githubusercontent.com/assets/2557625/26107445/0675181a-3a52-11e7-95ee-11134cef846e.jpg)
3. გარშემო მოვკლათ კენტავრები
4. არ ჩნდება

**Comment by neltharionorg** [comment]
https://www.youtube.com/watch?v=ZfCwY6FVhg4

**Comment by LevanSturua** [comment]
Perfect, Closed.
