### ISSUE TITLE
[Quest] Death Knight Zone - Death's Challenge

### ISSUE THREAD

**Issue by Melanholyx** [LevanSturua/common-core-db-bugs#12]
#**აღწერა:**
5 Death Knight-ს უნდა ედუელო და მოუგო, იქვე მოძრაობენ.
**როგორ მუშაობს:**
ფაქტიურად არ მუშაობს რადგან ეს Death knight-ები , ჩვეულებრივი Player-ებისთვის არიან Enemy თუმცა ისენი Enemy რომელსაც ატარგეტებ მაგრამ ვერ ურტყავ, და არც ისენი მოგზდევენ რო გირტყან. მოკლედ დუელს ვერ უმართავ . 
**როგორ უბდა მუშაობდეს:**
უნდა მუშაობდეს შემდეგნაირად : დაელაპარაკები ჩამოვარდება დუელი, იწყება ათვლა 3იდან და შემდეგ იწყება დუელი, ჩვეულებრივ მიმინარეობს დუელი არაფერი განსაკუთრებული და რათქმაუნდა უნდა დაამარცხოთ რომ შესრულდეს ასე აკეთებ 5ჯერ.
**როგორ შევამოწმოთ:**
.quest add 12733
ან გავყვეთ Dk-ს ქვესტებს, დაახლოებით მერვე ან მეცხრე ქვესტია, 5 წუთიანი ქვესტაობის შემდეგ მიადგებით.

**Comment by neltharionorg** [comment]
გასწორდა
![1](https://cloud.githubusercontent.com/assets/28743090/26273339/9875a51e-3d3f-11e7-9f75-df09acc13795.jpg)
![2](https://cloud.githubusercontent.com/assets/28743090/26273340/9895cbe6-3d3f-11e7-9554-bc250fc69355.jpg)
