### ISSUE TITLE
[Quest][Warlock] -  The Binding

### ISSUE THREAD

**Issue by fxizelgodx** [LevanSturua/common-core-db-bugs#13]
**აღწერა:**  ვერ ვეხები

**როგორ მუშაობს:** 
![wowscrnshot_051917_232706](https://cloud.githubusercontent.com/assets/28814256/26263864/849d39d4-3ceb-11e7-8cd2-823567fb736f.jpg)

**როგორ უბდა მუშაობდეს:**

**როგორ შევამოწმოთ:**

**Comment by LevanSturua** [comment]
რა ჭირს ამ ქვესთს ფხიზელ? რო კლავ არ გითვლის?

**Comment by GMegr** [comment]
ვერ ვესვრი ვერაფერს, ვერც ვურტყავ. იმპიც არ რეაგირებს ალბათ არასწორ კოორდინატებზე ჩნდება მიწაში და მაგის გამო

**Comment by LevanSturua** [comment]
არა, მიწის პრობლემა არ არის. "invalid target"ს გიწერს, ანუ ვერ უტევ.
მიწაში ან line of sightში რო არ იყოს, "target is out of line of sight"ს დაგიწერდა

**Comment by neltharionorg** [comment]
გასწორდა

![wowscrnshot_052017_090639](https://cloud.githubusercontent.com/assets/28743090/26273196/cd8536d8-3d3b-11e7-9ffd-9896e42a1cca.jpg)
![wowscrnshot_052017_090648](https://cloud.githubusercontent.com/assets/28743090/26273197/cd85710c-3d3b-11e7-9193-a5ed273a67d6.jpg)
![wowscrnshot_052017_090700](https://cloud.githubusercontent.com/assets/28743090/26273198/cd88b574-3d3b-11e7-911b-707aef489e4d.jpg)

**Comment by LevanSturua** [comment]
Closed.
