### ISSUE TITLE
[Class] [Mage] Mirror Image [Fire Blast]

### ISSUE THREAD

**Issue by Melanholyx** [LevanSturua/common-core-db-bugs#16]
**აღწერა:**
ესიგი mirror image- Frostbolt უნდა ურტყავდეს owner Spell Power-ის 10% Damage-ს ხოლო Fire Blast 5%-ს. 
**როგორ მუშაობს:**
Frostbolt-თან არანაირი პრობლემა არ გვაქვს, უბრალოდ Fire Blast ურტყავს 20% Spell power-ის Damage-ს.
**როგორ უბდა მუშაობდეს:**
Fire Blast უნდა ურტყავდეს 5% Spell power-ის Damage-ს
**როგორ შევამოწმოთ:**
.learn 55342
შევამოწმოთ რადმენი გვაქვს Spell Power.
მაგალითად 1000 თუ გვაქვს Frostbolt-მა უნდა გააკეთოს 100 damage , ხოლო Fireblast-მა 50 Damage.

**Comment by LevanSturua** [comment]
spell_bonus_data-ს პრობლემაა ჩემი აზრით. 

`SELECT * FROM `spell_bonus_data` WHERE (ID = 59637);`
რომელიც სავარაუდოთ დააბრუნებს 
`(59637,0.6,0,0,0,'Pet Mage - Mirror Image Fireblast')-ს `
^ეს შეცვალეთ ამით 
`(59637,0.15,0,0,0,'Pet Mage - Mirror Image Fireblast') `
და დატესტეთ მირორის Fireblast დემეიჯი.

**Comment by neltharionorg** [comment]
გასწორდა
![wowscrnshot_052117_085837](https://cloud.githubusercontent.com/assets/28743090/26281283/ddffc6f4-3e03-11e7-9149-1d0a0036555a.jpg)
![wowscrnshot_052117_085844](https://cloud.githubusercontent.com/assets/28743090/26281282/ddfebda4-3e03-11e7-8594-62a50988ea8f.jpg)

**Comment by neltharionorg** [comment]
@LevanSturua exla vnaxe sheni komentari igive metodit gavaswore mec 👍

**Comment by LevanSturua** [comment]
გასწორდა, closed.
