### ISSUE TITLE
[Class][Shaman] Ghost Wolf

### ISSUE THREAD

**Issue by Melanholyx** [LevanSturua/common-core-db-bugs#17]
**აღწერა:**
ესეიგი 16 ლეველზე სწავლობ სპელს და იქცევი მგლად და დარბიხარ უფრო სწრაფად ვიდრე ჩვეულებრივ
**როგორ მუშაობს:**
ანუ ეს ყვეალფერი კარგი მარა საქმე იმაშია რო მგელში რო გადავდივარ +100-150 Damage მემატება,.
ეს დაბალ ლეველზე დიდი ბუსტია, 80ზეუკვე აღარაფერს ნიშნავს იმიტო რო ყველა ლეველზე აზრი არ აქ მაიცნ 100-150 dmg-ა
**როგორ უბდა მუშაობდეს:**
უნდა მუშაობდეს ისე როგორც არის უბრალოდ ეს DMG არ უნდა ემატებოდეს
**როგორ შევამოწმოთ:**
ვისწავლოთ Ghost Wolf
.learn 2645 გადავიდეთ ფორმაში და შევამოწმოთ ჩვენი Melee Damage

**Comment by LevanSturua** [comment]
ვაფშეტა მაგარი კრიტუკული ბაგია, playerმა რო გაიგოს და გამოიყენოს, ძაან გაიმარტივებს low ლეველ კონტენტს.

**Comment by neltharionorg** [comment]
16 ლეველზე გაქვს 51 
![wowscrnshot_052117_152050](https://cloud.githubusercontent.com/assets/28743090/26283419/282f9a1c-3e39-11e7-8cfa-11e73a20e99a.jpg)
40 ლეველზე 123
![wowscrnshot_052117_152017](https://cloud.githubusercontent.com/assets/28743090/26283425/397dc7f8-3e39-11e7-83b9-8cbb908f6e66.jpg)
ორივე შემთხვევაში სპელის DMG უფრო მეტია ვიდრე Ghost Wolfის
60-80 ურტყავს 40 ლეველზე სანამ 60-80 მობს მოკლავ ის მოგკლავს შენ ასერომ არანაირად არ არის კრიტიკული და საგანგაშო.

**Comment by neltharionorg** [comment]
ყველაფერს რო თავი დავანებოთ 2 წუთი მაინც გინდა მობის მოვკლისთვის

**Comment by LevanSturua** [comment]
გასაგებია, სხვანაირი ბაგი მეგონა. 
ისე აღწერეს რომ მეგონა ჩვეულებრივ weapon dmg-ს (რამდენიც გექნებოდა) ზევიდან ამატებდა 100-150-ს მგლის ფორმაში 

მგონი ბაგი არცაა ეხა როგორცაა

**Comment by justdothings** [comment]
არა იარაღის DMG არ ემატება
