### ISSUE TITLE
[NPC] - Succubus Minion

### ISSUE THREAD

**Issue by LevanSturua** [LevanSturua/common-core-db-bugs#18]
**აღწერა:** Warlock მობებს, ხანდახან ყავთ ხოლმე პეტაბად იმპები და სუკუბუსები.

**როგორ მუშაობს:** Succubus Minionს აქვს 2 პრობლემა. 
1) არ ეხმარება ვარლოკ მობს სანამ იმენა სუკუბუსს არ მოხვდება damage.
2) "lash of pain"-ით ძაან დიდს ირტყმევინებიან
![wowscrnshot_052117_163839](https://cloud.githubusercontent.com/assets/2557625/26284133/b846df7c-3e3c-11e7-91b4-118d67e87ff7.jpg)

**როგორ უბდა მუშაობდეს:** 
1) warlock მობს რომ დააყრი, უნდა მიეხმარონ, 
2) "lash of pain"-ის damage გასასწორებელია

**როგორ შევამოწმოთ:**
1) stranglethorn Warlockებთან მიდით აქ 
![wowscrnshot_052117_164900](https://cloud.githubusercontent.com/assets/2557625/26284147/2afe44f6-3e3d-11e7-9caf-9bb30b0d0d79.jpg)
2) ნახავთ რომ ვარლოკს რომ დააყრით, სუკუბუსი არ მიეხმარება
3) სუკუბუსს თუ დააყრით, ნახავთ "lash of pain"ის damageს, ერთი 45-ზე მაღალი ლეველი არ იყოთ, თორე spellია და უმეტესობას გაmissავს.

**Comment by neltharionorg** [comment]
დაეწია DMG
![wowscrnshot_052517_134536](https://cloud.githubusercontent.com/assets/28743090/26445903/f40c2c24-4152-11e7-85f7-1b1c34d0b3d3.jpg)

**Comment by LevanSturua** [comment]
nice, closed.
