### ISSUE TITLE
[Quest] [Borean Tundra] - The Warsong Farms.

### ISSUE THREAD

**Issue by Melanholyx** [LevanSturua/common-core-db-bugs#19]
##**აღწერა:**
ესეიგი ქვესტია უბრალოდ რაღაც დროშებია დარჭობილი ვარსონგის და უნდა აღმოაჩინო
**როგორ მუშაობს:**
რეალურად არის დარჭობილი ჩვეულებრივ დროშები და ანათებს კიდევრომ ქვესტისაა თუმცა ახლოს რომ მიდიხარ არაფერი ხდება,
**როგორ უბდა მუშაობდეს:**
უბრალოდ უნდა მიხვიდე რუკაზე დანიშნულების ადგილზე სადაც არის დროშები დარჭობილი და ახლოს რომ მიხვალ explore გაგიკეთებს იმ ლოკაციის და ჩაგითლის ამ დროშის აღმოჩენასაც.
**როგორ შევამოწმოთ:**
.quest add 11686

**Comment by LevanSturua** [comment]
ეს ქვესთი მუშაობდა, საინტერესოა რამ გამოიწვია გაბაგვა. 

საკმაოდ მნიშვნელოვან chainს ბლოკავს ამ ქვესთის არ მუშაობა

**Comment by neltharionorg** [comment]
გასწორდა
![wowscrnshot_052417_132508](https://cloud.githubusercontent.com/assets/28743090/26396639/de77da44-4084-11e7-8082-c9644997e50f.jpg)
