### ISSUE TITLE
[Quest][Horde][Barrens] - Hezrul Bloodmark

### ISSUE THREAD

**Issue by LevanSturua** [LevanSturua/common-core-db-bugs#2]
**აღწერა:** მცველები მიბმული არ ყავს

**როგორ მუშაობს:** შორიდან რომ აიკიდო ამ მობის მცველები არ გამოგეკიდებიან

**როგორ უნდა მუშაობდეს:** ეს მობი Hezrul Bloodmark თავის 2 მცველთან ერთად უნდა დადიოდეს ბარენსის ერთერთი ოაზისის გარშემო, აკიდების შემთხვევაში მცველებიც უნდა აგეკიდონ.

**როგორ შევამოწმოთ:** 
1. .add quest 852
2. .go creature id 3396
3. შორიდან ავიკიდოთ რამე სპელით
4. 2 დაცვა არ გამოგეკიდება

**დამატებითი პრობლემა:**  #1 ქვესთის გაკეთების გარეშე მოთამაშე ^ ქვესთამდე ვერც მივა

**Comment by LevanSturua** [comment]
creature_template-ის პრობლემაა და ადვილი გასასწორებელია

unit_flags-ი იქნება 2 დაცვის მისაბმელი Hezrul Bloodmark-თან.
https://trinitycore.atlassian.net/wiki/display/tc/creature_template

**Comment by neltharionorg** [comment]
https://www.youtube.com/watch?v=8AGhoDaCfRQ

**Comment by LevanSturua** [comment]
woah, cool.
