### ISSUE TITLE
 [Quest][Tanaris] - Water Pouch Bounty

### ISSUE THREAD

**Issue by fxizelgodx** [LevanSturua/common-core-db-bugs#20]
**აღწერა:** 
![wowscrnshot_052517_230117](https://cloud.githubusercontent.com/assets/28814256/26466126/a2e7f5de-419e-11e7-8bea-28ce2164ebda.jpg)   უნდა ყრიდნენ  ამეებს და არ ყრიან
![image](https://cloud.githubusercontent.com/assets/28814256/26466189/e102173c-419e-11e7-8bcb-a211debacdbe.png) 

**როგორ მუშაობს:** არ ყრიან

**როგორ უბდა მუშაობდეს:** უნდა ყრიდნენ

**როგორ შევამოწმოთ:** მიდიხართ მობთან რომელიც სურათზეა და წერთ .kill, ლუტავთ გვამს და ნახავთ რომ არ ყრიან

**Comment by LevanSturua** [comment]
2-3დღის წინ რო გავაკეთე ეგ ქვესთი ჩვეულებრივად სრულდებოდა

**Comment by neltharionorg** [comment]
მუშაობს დაბალია დროფის შანსი უბრალოდ
![wowscrnshot_052617_121335](https://cloud.githubusercontent.com/assets/28743090/26486706/495d9b8a-420d-11e7-8f12-d931b666ac60.jpg)
![wowscrnshot_052617_121337](https://cloud.githubusercontent.com/assets/28743090/26486707/4966f7ac-420d-11e7-89c5-aa8d2132ed37.jpg)
