### ISSUE TITLE
[Quest][Icecrown] - The Battle For Crusaders' Pinnacle

### ISSUE THREAD

**Issue by LevanSturua** [LevanSturua/common-core-db-bugs#22]
**აღწერა:** Venture to Crusaders' Pinnacle and use the Blessed Banner of the Crusade atop the Pile of Crusader Skulls. Defend the banner against Scourge attack until the land atop the pinnacle is sanctified and then return to Father Gustav at the Valley of Echoes in Icecrown.

**როგორ მუშაობს:** უნდა დაარჭო banner (quest item) ამ ადგილას და დაიცვათ scourgeის შემოტევისგან. ბაგი მდგომარეობს იმაში რომ, argent crusader-ის კამანდა ვინც უნდა გეხმარებოდეს დაცვაში, პირიქით bannerს ანგრევენ. ძაან სერიოზული ბაგია, რადგან უამრავი ქვესთი იბლოკება ამ ქვესთის შესრულების გარეშე.
![cp](https://cloud.githubusercontent.com/assets/2557625/26550707/aaf594c0-4487-11e7-895c-ecce64dfb00d.JPG)
![110663-the-battle-for-crusaders-pinnacle](https://cloud.githubusercontent.com/assets/2557625/26550708/acb98dfc-4487-11e7-862c-20e0c3a1bdbc.jpg)

**როგორ უბდა მუშაობდეს:**
https://www.youtube.com/watch?v=wO-EPcRPWAo

**როგორ შევამოწმოთ:**
1) .quest add 13141
2) მივიდეთ ზევით დადებული screenshotების ადგილას
3) დავდგათ banner და შევამოწმოთ

**Comment by neltharionorg** [comment]
https://youtu.be/GyHPNlRl31Y

**Comment by LevanSturua** [comment]
closed
