### ISSUE TITLE
[Quest][Horde][Thousand Needles] - Protect Kanati Greycloud

### ISSUE THREAD

**Issue by LevanSturua** [LevanSturua/common-core-db-bugs#4]
**აღწერა:** კენტავრების შემოტევისგან უნდა დაიცვა ბაზა და Kanati Greycloud

**როგორ მუშაობს:** Autocomplete-ზეა, ქვესთს როცა აიღებ  ცოტა ხანში ავტომატურად სრულდება.

**როგორ უნდა მუშაობდეს:** ბაზას და Kanati Greycloud კენტავრები უნდა უტევდნენ, რომელიც უნდა დაიცვა

**როგორ შევამოწმოთ:**
1. .go creature id 10638
2. .quest add 4966
3. wait
4. autocomplete-ს მისცემს ცოტა ხანში

**Comment by neltharionorg** [comment]
kibatono ar mushaobs, eventi iwyeba kentavrebi gamodian da mere auto completes aketebs, dges davamtavreb updatebs da mivyvebi mere danarchen dareportebul questebsac.

**Comment by LevanSturua** [comment]
დაიფიქსა, closed.
