### ISSUE TITLE
[Quest][Horde][Dragonblight] - Sarathstra, Scourge of the North

### ISSUE THREAD

**Issue by LevanSturua** [LevanSturua/common-core-db-bugs#9]
**აღწერა:** Rokhan-ს უნდა დაელაპარაკო რომ დრაკონი Sarathstra გამოიძახოს და მოკლა.

**როგორ მუშაობს:** AI მთლიანად გაბაგული აქვს, melee დარტყმების გარდა არაფერს აკეთებს, თან ბოლომდე არ ჩამოდის მიწაზე, ასე რომ მელეე კლასები საერთოდ ვერ დაარტყამენ

**როგორ უბდა მუშაობდეს:**  დასკრიპტული AI უნდა ქონდეს შემდეგი spell-ებით: Blizzard; Frost Breath; Shadow nova 
http://www.wowhead.com/npc=26858/sarathstra#abilities
https://www.youtube.com/watch?v=W83yBE_jbxE

**როგორ შევამოწმოთ:**
1. .go creature id 26859
2. .quest add 12097
3. დაველაპარაკოთ Rokhan, რომ გამოიძახოს Sarathstra 
4. ვნახოთ როგორ მუშაობს

**Comment by neltharionorg** [comment]
Miwaze chamosvla gavaswore Spellebs xval mivxedav ✌️

**Comment by neltharionorg** [comment]
spelebs ra tanmimdevrobit aketebs da ramden wamshi ertxel shegidzlia minaxo?

**Comment by LevanSturua** [comment]
ტაკ, smart scriptი დავწერე. მაქსიმალურად შევეცადე ბლიზლაიკს მიმესგვასებინა
დასატესტი იქნება:



```
INSERT INTO `world`.`smart_scripts` (`entryorguid`, `id`, `event_param1`, `event_param2`, `event_param3`,
 `event_param4`, `action_type`, `action_param1`, `target_type`, `comment`) VALUES ('26858', '8', '5000',
 '8000', '6000', '9000', '11', '47425', '2', 'Frost Breath');

INSERT INTO `world`.`smart_scripts` (`entryorguid`, `id`, `event_param1`, `event_param2`, `event_param3`,
 `event_param4`, `action_type`, `action_param1`, `target_type`, `comment`) VALUES ('26858', '9', '15000',
 '18000', '40000', '43000', '11', '61085', '5', 'blizzard');

INSERT INTO `world`.`smart_scripts` (`entryorguid`, `id`, `event_param1`, `event_param2`, `event_param3`, 
`event_param4`, `action_type`, `action_param1`, `target_type`, `comment`) VALUES ('26858', '10', '45000',
 '48000', '45000', '48000', '11', '39005', '1', 'Shadow Nova');
```

**Comment by neltharionorg** [comment]
ვცადე უკვე სმარტი მაგრამ სავარაუდოთ ც++!უმდა ამ ვერსიასაც გავტესტავ ხვალ

**Comment by LevanSturua** [comment]
არა, არ უნდა მაგას c++, არაა ძაან კომპლექსური NPC.
 არა-ბოსს NPCებისთვის smart_scriptი საკმარისია.

**Comment by neltharionorg** [comment]
კარგია მუშაობს
![wowscrnshot_052417_113618](https://cloud.githubusercontent.com/assets/28743090/26391805/40dffb4a-4075-11e7-8578-006f7ddd9216.jpg)

**Comment by LevanSturua** [comment]
კაია, closed.
